artifacts_root: artifacts

data_ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://github.com/dheeraj24797/MediWatch_project/blob/main/diabetic_data.zip
 local_data_file: artifacts/data_ingestion/data.zip
 unzip_dir: artifacts/data_ingestion